"""tr

Revision ID: 48661bca2b6a
Revises: e6d9474c7ba8
Create Date: 2025-06-27 22:37:44.798261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48661bca2b6a'
down_revision = 'e6d9474c7ba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 