"""remove parent_file_id from File model

Revision ID: 9b5be8da2e47
Revises: a5f468207ede
Create Date: 2025-07-16 14:19:47.994798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b5be8da2e47'
down_revision = 'a5f468207ede'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_processed_image_created_at'), table_name='processed_images')
    op.drop_index(op.f('idx_processed_image_file_type'), table_name='processed_images')
    op.drop_index(op.f('idx_processed_image_type'), table_name='processed_images')
    op.drop_index(op.f('ix_processed_images_file_id'), table_name='processed_images')
    op.drop_index(op.f('ix_processed_images_id'), table_name='processed_images')
    op.drop_index(op.f('ix_processed_images_processed_image_type'), table_name='processed_images')
    op.drop_table('processed_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('processed_image_type', postgresql.ENUM('NDMI', 'NDVI', name='processedimagetype'), autoincrement=False, nullable=False),
    sa.Column('processed_image_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('processed_filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('processing_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processing_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('processed_images_file_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('processed_images_pkey'))
    )
    op.create_index(op.f('ix_processed_images_processed_image_type'), 'processed_images', ['processed_image_type'], unique=False)
    op.create_index(op.f('ix_processed_images_id'), 'processed_images', ['id'], unique=False)
    op.create_index(op.f('ix_processed_images_file_id'), 'processed_images', ['file_id'], unique=False)
    op.create_index(op.f('idx_processed_image_type'), 'processed_images', ['processed_image_type'], unique=False)
    op.create_index(op.f('idx_processed_image_file_type'), 'processed_images', ['file_id', 'processed_image_type'], unique=False)
    op.create_index(op.f('idx_processed_image_created_at'), 'processed_images', ['created_at'], unique=False)
    # ### end Alembic commands ### 