"""Initial migration - user and auth tables1

Revision ID: 9f3ed578c43c
Revises: a039fd2c2a94
Create Date: 2025-06-26 21:48:11.716402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3ed578c43c'
down_revision = 'a039fd2c2a94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 