"""first

Revision ID: a039fd2c2a94
Revises: 3de697e30885
Create Date: 2025-06-26 21:47:59.211091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a039fd2c2a94'
down_revision = '3de697e30885'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 