"""first1

Revision ID: c4b9bcc5209c
Revises: 9f3ed578c43c
Create Date: 2025-06-26 21:48:24.993501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b9bcc5209c'
down_revision = '9f3ed578c43c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 